# For implementation details, see SecurityConfiguration.java
authentication:
  # TODO: add PRD issuer URIs
  issuerUris: []
  # TODO: add PRD JWK Set URI
  jwkSetUri:
  # TODO: add PRD audiences
  audiences: []

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

aws:
  dynamodb:
    tableName: journal-data
    local: false
  cloudfront:
    keyPairId: abc #TODO fill this in when setup
    distributionDomain: "d123abc.cloudfront.net" #TODO fill this in when setup
    privateKeySecretName: cloudformation-private-key
  s3:
    bucketName: journal-data-photos